import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { pathToFileURL } from 'node:url';
import { createServer } from '../server.js';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'heartping-browser-'));
const server = createServer({ dataFile: path.join(folder,'state.json') });
await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser=await chromium.launch({headless:true, ...(process.env.BROWSER_CHANNEL ? {channel:process.env.BROWSER_CHANNEL} : {})});
  const errors=[];
  const aContext=await browser.newContext({viewport:{width:390,height:844}});
  const bContext=await browser.newContext({viewport:{width:320,height:740}});
  const a=await aContext.newPage(), b=await bContext.newPage();
  for (const page of [a,b]) page.on('pageerror',error=>errors.push(error.message));
  await Promise.all([a.goto(base),b.goto(base)]);
  assert.equal(await a.locator('#btn-start-pairing').isDisabled(),true);
  await a.locator('#input-my-name').fill('Alex');
  await a.locator('#btn-start-pairing').click();
  await a.locator('#screen-pairing.active').waitFor();
  const code=await a.locator('#my-pairing-code').innerText();
  assert.match(code,/^\d{6}$/);
  await b.locator('#input-my-name').fill('Maya <img src=x>');
  await b.locator('#btn-start-pairing').click();
  await b.locator('#screen-pairing.active').waitFor();
  await b.locator('#input-partner-code').fill('000000');
  await b.locator('#btn-connect-partner').click();
  await b.waitForFunction(()=>document.querySelector('#toast-desc').textContent.includes('not found'));
  assert.equal(await b.locator('#screen-pairing').getAttribute('class'),'screen active');
  await b.locator('#input-partner-code').fill(code);
  await b.locator('#btn-connect-partner').click();
  await Promise.all([a.locator('#screen-main.active').waitFor(),b.locator('#screen-main.active').waitFor()]);
  await a.locator('#btn-heart-ping').click();
  await b.waitForFunction(()=>document.querySelector('#history-list').textContent.includes('Alex → You'));
  await b.locator('#btn-heart-ping').click();
  await a.waitForFunction(()=>document.querySelector('#history-list').textContent.includes('Maya <img src=x> → You'));
  assert.equal(await a.locator('#history-list img').count(),0);
  assert.equal(await a.locator('#btn-simulate-partner-ping').isVisible(),false);
  await Promise.all([a.reload(),b.reload()]);
  await Promise.all([a.locator('#screen-main.active').waitFor(),b.locator('#screen-main.active').waitFor()]);
  assert.equal(await a.locator('.history-item').count(),2);
  assert.equal(await b.locator('.history-item').count(),2);
  await bContext.setOffline(true);
  await b.locator('#btn-heart-ping').click();
  await b.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('Cannot reach'));
  assert.equal(await b.locator('.history-item').count(),2);
  await bContext.setOffline(false);
  await b.locator('#btn-heart-ping').click();
  await a.waitForFunction(()=>document.querySelectorAll('.history-item').length===3);
  assert.equal(await b.locator('.history-item').count(),3);
  assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await a.evaluate(()=>navigator.serviceWorker.ready);
  await a.reload();
  await a.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  const cached = await a.evaluate(async()=> (await caches.open('heartping-v3')).keys().then(keys=>keys.map(key=>key.url)));
  assert.ok(cached.some(url=>url.endsWith('/icons/icon-512.png')));
  assert.ok(!cached.some(url=>url.includes('/api/')));
  await aContext.setOffline(true);
  await a.reload();
  await a.locator('#screen-welcome.active').waitFor();
  await a.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('Cannot reach'));
  await aContext.setOffline(false);
  await a.locator('#screen-main.active').waitFor();
  await fs.promises.mkdir('.audit/screenshots',{recursive:true});
  await a.waitForFunction(()=>!document.querySelector('#toast-banner').classList.contains('show'));
  await a.screenshot({path:'.audit/screenshots/paired.png',fullPage:true,animations:"disabled"});
  await a.locator('#btn-settings').click();
  a.once('dialog',dialog=>dialog.accept());
  await a.locator('#btn-unpair').click();
  await Promise.all([a.locator('#screen-pairing.active').waitFor(),b.locator('#screen-pairing.active').waitFor()]);
  assert.notEqual(await a.locator('#my-pairing-code').innerText(),code);
  await a.waitForFunction(()=>!document.querySelector('#toast-banner').classList.contains('show'));
  await a.screenshot({path:'.audit/screenshots/pairing.png',fullPage:true,animations:"disabled"});
  await a.locator('#btn-quick-demo').click();
  await a.locator('#screen-main.active').waitFor();
  assert.ok((await a.locator('#connection-status').innerText()).includes('Local demo'));
  await a.locator('#btn-simulate-partner-ping').click();
  assert.equal(await a.locator('.history-item').count(),1);
  const fresh=await browser.newPage();
  await fresh.goto(base);
  await fresh.screenshot({path:'.audit/screenshots/welcome.png',fullPage:true,animations:"disabled"});
  assert.deepEqual(errors,[]);
  console.log('PASS: independent mobile sessions, validation, pairing, bidirectional pings, safe name rendering, reload persistence, offline shell/recovery, SW cache isolation, unpair and explicit demo.');
} finally {
  await browser?.close();
  await new Promise(resolve=>server.close(resolve));
  fs.rmSync(folder,{recursive:true,force:true});
}

